import type { Metadata } from "next";
import poppins from "@/lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "NIYI ENTERPRISE",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "Generated by create next app",
    images: [
      {
        url: "/opengraph.png",
        width: 1200,
        height: 630,
        alt: "NIYI ENTERPRISE",
      },
    ],
    siteName: "NIYI ENTERPRISE",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
